<a href="https://colab.research.google.com/github/joosomi/BigDataStudy/blob/main/%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/AnalyticsKnight/yemoonsaBigdata/

Cloning into 'yemoonsaBigdata'...
remote: Enumerating objects: 637, done.
remote: Counting objects: 100% (274/274), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 637 (delta 136), reused 184 (delta 109), pack-reused 363
Receiving objects: 100% (637/637), 10.76 MiB | 12.83 MiB/s, done.
Resolving deltas: 100% (321/321), done.


In [3]:
import pandas as pd
X_train = pd.read_csv("yemoonsaBigdata/datasets/Part3/504_x_train.csv")
X_test = pd.read_csv("yemoonsaBigdata/datasets/Part3/504_x_test.csv")
y_train = pd.read_csv("yemoonsaBigdata/datasets/Part3/504_y_train.csv")

In [4]:
X_train.head()

id model  year transmission  mileage fuelType  tax   mpg  engineSize
0   1    A1  2019    Automatic     3500   Petrol  145  40.9         2.0
1   2   RS4  2020    Semi-Auto     2500   Petrol  145  28.8         2.9
2   3    A8  2019    Semi-Auto      500   Diesel  145  40.4         3.0
3   4    Q5  2019    Semi-Auto     5089   Diesel  150  38.2         2.0
4   5    A5  2020    Semi-Auto     4951   Diesel  145  51.4         2.0

In [5]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7468 entries, 0 to 7467
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            7468 non-null   int64  
 1   model         7468 non-null   object 
 2   year          7468 non-null   int64  
 3   transmission  7468 non-null   object 
 4   mileage       7468 non-null   int64  
 5   fuelType      7468 non-null   object 
 6   tax           7468 non-null   int64  
 7   mpg           7468 non-null   float64
 8   engineSize    7468 non-null   float64
dtypes: float64(2), int64(4), object(3)
memory usage: 525.2+ KB


In [6]:
X_train.isnull().sum()

id              0
model           0
year            0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [7]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            3200 non-null   int64  
 1   model         3200 non-null   object 
 2   year          3200 non-null   int64  
 3   transmission  3200 non-null   object 
 4   mileage       3200 non-null   int64  
 5   fuelType      3200 non-null   object 
 6   tax           3200 non-null   int64  
 7   mpg           3200 non-null   float64
 8   engineSize    3200 non-null   float64
dtypes: float64(2), int64(4), object(3)
memory usage: 225.1+ KB


In [8]:
X_test.isnull().sum()

id              0
model           0
year            0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [9]:
y_train.head()

id  price
0   1  21350
1   2  69691
2   3  42950
3   4  31470
4   5  27495

In [10]:
col_del = ['id']
col_num = ['year', 'mileage', 'tax', 'mpg', 'engineSize']
col_cat = ['model', 'transmission', 'fuelType']
col_y = ['price']

In [13]:
from sklearn.preprocessing import MinMaxScaler
import sklearn
# help(sklearn.preprocessing.MinMaxScaler)
min = MinMaxScaler()
min.fit(X_train[col_num])
X_train[col_num] = min.transform(X_train[col_num])
X_test[col_num] = min.transform(X_test[col_num])

In [14]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()


X_train[col_cat] = X_train[col_cat].apply(label.fit_transform)
X_test[col_cat] = X_test[col_cat].apply(label.fit_transform)

In [15]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7468 entries, 0 to 7467
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            7468 non-null   int64  
 1   model         7468 non-null   int64  
 2   year          7468 non-null   float64
 3   transmission  7468 non-null   int64  
 4   mileage       7468 non-null   float64
 5   fuelType      7468 non-null   int64  
 6   tax           7468 non-null   float64
 7   mpg           7468 non-null   float64
 8   engineSize    7468 non-null   float64
dtypes: float64(5), int64(4)
memory usage: 525.2 KB


In [16]:
X_train.head()

id  model      year  transmission   mileage  fuelType       tax       mpg  \
0   1      0  0.954545             0  0.020825         2  0.250000  0.127811   
1   2     15  1.000000             2  0.014874         2  0.250000  0.056213   
2   3      7  0.954545             2  0.002970         0  0.250000  0.124852   
3   4     10  0.954545             2  0.030283         0  0.258621  0.111834   
4   5      4  1.000000             2  0.029461         0  0.250000  0.189941   

   engineSize  
0    0.317460  
1    0.460317  
2    0.476190  
3    0.317460  
4    0.317460

In [21]:
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(X_train[col_num + col_cat], y_train[col_y], test_size=0.2)

In [22]:
from sklearn.ensemble import RandomForestRegressor
model1 = RandomForestRegressor()
model1.fit(X_tr,y_tr)

<ipython-input-22-7a417999c35c>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model1.fit(X_tr,y_tr)


RandomForestRegressor()

In [23]:
pred1 = model1.predict(X_val)
pred1

array([31694.65      , 44045.34333333, 17413.75      , ...,
       18389.61      , 14162.74      ,  8802.36      ])

In [24]:
from xgboost import XGBRegressor
model2 = XGBRegressor()
model2.fit(X_tr,y_tr)
pred2= model2.predict(X_val)
pred2

array([31935.662, 48022.652, 17089.32 , ..., 17794.186, 14697.526,
        8698.343], dtype=float32)

In [25]:
from sklearn.metrics import mean_squared_error
import numpy as np

print('model1', np.sqrt(mean_squared_error(y_val, pred1)))
print('model2', np.sqrt(mean_squared_error(y_val, pred2)))


model1 2542.399579137993
model2 2425.9783037790194


In [26]:
#정답
answer = model2.predict(X_test[col_num + col_cat])
answer

array([38044.727, 17087.19 , 30606.521, ..., 19581.766, 23976.348,
       17572.303], dtype=float32)

In [27]:
result = pd.DataFrame({'id': X_test.id, 'price': answer})
print(result.head())

     id         price
0  7469  38044.726562
1  7470  17087.189453
2  7471  30606.521484
3  7472  15680.189453
4  7473  15352.924805


In [28]:
result.to_csv("00ddd.csv", index=False)

In [32]:
import pandas as pd
X_test = pd.read_csv("yemoonsaBigdata/datasets/Part3/404_x_test.csv")
X_train = pd.read_csv("yemoonsaBigdata/datasets/Part3/404_x_train.csv")
y_train = pd.read_csv("yemoonsaBigdata/datasets/Part3/404_y_train.csv")

In [33]:
print(X_test.head())

       ID  Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
0  458989  Female          Yes   36       Yes    Engineer              0.0   
1  458994    Male          Yes   37       Yes  Healthcare              8.0   
2  459000    Male          Yes   59        No   Executive             11.0   
3  459003    Male          Yes   47       Yes      Doctor              0.0   
4  459005    Male          Yes   61       Yes      Doctor              5.0   

  Spending_Score  Family_Size  
0            Low          1.0  
1        Average          4.0  
2           High          2.0  
3           High          5.0  
4            Low          3.0  


In [34]:
X_train.head()

ID  Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
0  462809    Male           No   22        No  Healthcare              1.0   
1  466315  Female          Yes   67       Yes    Engineer              1.0   
2  461735    Male          Yes   67       Yes      Lawyer              0.0   
3  461319    Male          Yes   56        No      Artist              0.0   
4  460156    Male           No   32       Yes  Healthcare              1.0   

  Spending_Score  Family_Size  
0            Low          4.0  
1            Low          1.0  
2           High          2.0  
3        Average          2.0  
4            Low          3.0

In [35]:
y_train.head()

ID Segmentation
0  462809            D
1  466315            B
2  461735            B
3  461319            C
4  460156            C

In [37]:
X_train.isnull().sum()

ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
dtype: int64

In [38]:
X_test.isnull().sum()

ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
dtype: int64

In [39]:
y_train.isnull().sum()

ID              0
Segmentation    0
dtype: int64

In [36]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6718 entries, 0 to 6717
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ID               6718 non-null   int64  
 1   Gender           6718 non-null   object 
 2   Ever_Married     6718 non-null   object 
 3   Age              6718 non-null   int64  
 4   Graduated        6718 non-null   object 
 5   Profession       6718 non-null   object 
 6   Work_Experience  6718 non-null   float64
 7   Spending_Score   6718 non-null   object 
 8   Family_Size      6718 non-null   float64
dtypes: float64(2), int64(2), object(5)
memory usage: 472.5+ KB


In [42]:
col_del=['ID']
col_num =['Age','Work_Experience','Family_Size']
col_cat = ['Gender','Ever_Married','Graduated','Profession','Spending_Score']
col_y = ['Segmentation']

In [43]:
from sklearn.preprocessing import MinMaxScaler
min = MinMaxScaler()
min.fit(X_train[col_num])

X_train[col_num] = min.transform(X_train[col_num])
X_test[col_num] = min.transform(X_test[col_num])


In [44]:
X_train.head()

ID  Gender Ever_Married       Age Graduated  Profession  \
0  462809    Male           No  0.056338        No  Healthcare   
1  466315  Female          Yes  0.690141       Yes    Engineer   
2  461735    Male          Yes  0.690141       Yes      Lawyer   
3  461319    Male          Yes  0.535211        No      Artist   
4  460156    Male           No  0.197183       Yes  Healthcare   

   Work_Experience Spending_Score  Family_Size  
0         0.071429            Low        0.375  
1         0.071429            Low        0.000  
2         0.000000           High        0.125  
3         0.000000        Average        0.125  
4         0.071429            Low        0.250

In [60]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
X_train[col_cat] = X_train[col_cat].apply(label.fit_transform)
X_test[col_cat] = X_test[col_cat].apply(label.fit_transform)

In [46]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6718 entries, 0 to 6717
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ID               6718 non-null   int64  
 1   Gender           6718 non-null   int64  
 2   Ever_Married     6718 non-null   int64  
 3   Age              6718 non-null   float64
 4   Graduated        6718 non-null   int64  
 5   Profession       6718 non-null   int64  
 6   Work_Experience  6718 non-null   float64
 7   Spending_Score   6718 non-null   int64  
 8   Family_Size      6718 non-null   float64
dtypes: float64(3), int64(6)
memory usage: 472.5 KB


In [47]:
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(X_train[col_num + col_cat], y_train[col_y], test_size = 0.2, stratify = y_train[col_y])


In [73]:
from sklearn.ensemble import RandomForestClassifier
model1 = RandomForestClassifier(max_depth = 5 , n_estimators=100)
model1.fit(X_tr, y_tr)

<ipython-input-73-354ac843c013>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model1.fit(X_tr, y_tr)


RandomForestClassifier(max_depth=5)

In [74]:
pred1 = model1.predict(X_val)
pred1

array(['A', 'D', 'D', ..., 'C', 'C', 'A'], dtype=object)

In [66]:
# from xgboost import XGBClassifier

In [75]:
from sklearn.metrics import f1_score

print(f1_score(y_val, pred1, average ='macro'))

0.5058487224256796


In [ ]:
# 0.4746803353790116
# 튜닝 - max_depth = 5 / n_estimators=50 0.5056286145424771
# 튜닝 - max_depth =5 / n_estimators=100  0.5058487224256796

In [76]:
#
ans = model1.predict(X_test[col_num + col_cat])
ans

array(['A', 'C', 'B', ..., 'A', 'C', 'D'], dtype=object)

In [77]:
result = pd.DataFrame({
    'ID': X_test.ID,
    "Segmentation": ans
})
result

ID Segmentation
0     458989            A
1     458994            C
2     459000            B
3     459003            C
4     459005            A
...      ...          ...
2173  467950            A
2174  467954            D
2175  467958            A
2176  467961            C
2177  467968            D

[2178 rows x 2 columns]

In [78]:
result.to_csv("Dsds.csv", index=False)

In [79]:
pd.read_csv("Dsds.csv").head()

ID Segmentation
0  458989            A
1  458994            C
2  459000            B
3  459003            C
4  459005            A