<a href="https://colab.research.google.com/github/joosomi/BigDataStudy/blob/main/%EC%9E%91%EC%97%85%ED%98%95_1%EB%B2%88%2C_2%EB%B2%88_%EB%8C%80%EB%B9%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 작업형 유형 1문제

In [1]:
# 작업형 유형 1문제 
# 알코올이 상위 10번째 값으로 상위 1-10위의 범위의 값을 변경한 후 
# speeding 가 7이상의 alcohol 데이터의 평균 산출
# 최종 결과만 프린트 출력 
import seaborn as sns
import pandas as pd
sns.get_dataset_names()
df = sns.load_dataset('car_crashes')
print(df.head())

   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA  


In [7]:
data = df.sort_values(by=df.columns[2], ascending=False) #알콜을 기준으로 내림차순 정렬
# data.head()
ten = data.iloc[9,2]   #10번째 값
data.iloc[:10, 2] = ten
data.head(11)

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
34   23.9     5.497    5.771          23.661       20.554       688.75   
40   23.9     9.082    5.771          22.944       19.359       858.97   
26   21.4     8.346    5.771          17.976       18.190       816.21   
43   19.4     7.760    5.771          17.654       16.878      1004.75   
11   17.5     9.450    5.771          14.350       15.225       861.18   
18   20.5     7.175    5.771          14.965       20.090      1281.55   
48   23.8     8.092    5.771          23.086       20.706       992.61   
41   19.4     6.014    5.771          19.012       16.684       669.31   
3    22.4     4.032    5.771          21.056       21.280       827.34   
36   19.9     6.368    5.771          18.308       18.706       881.51   
42   19.5     4.095    5.655          15.990       15.795       767.91   

    ins_losses abbrev  
34      109.72     ND  
40      116.29     SC  
26       85.15     MT  
43      156.83     TX  
11      120.92     HI  
18      194.78     LA  
48      152.56     WV  
41       96.87     SD  
3       142.39     AR  
36      178.86     OK  
42      155.57     TN

In [9]:
result = data[(data['speeding']>=7)]
print('최종 결과물은', result['alcohol'].mean())

최종 결과물은 5.600099999999999


데이터 첫번째 행부터 70%까지의 데이터 추출한 후   
distance의 결측값을 distance의 중앙값으로 대체하고  
결측값 전처리 전과 후의 표준편차를 비교  
전/후 결과값 print 출력  

In [11]:
import seaborn as sns
import pandas as pd
import numpy as np 
df = sns.load_dataset('planets')
print(df.head())

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009


In [49]:
# len(df) #데이터의 길이 - 1035
del len
len = int(len(df)*0.7) # 724개
df = df[:len]
df2= df.copy() #전처리 전후 비교하려고 
df2['distance'] = df2['distance'].fillna(df2['distance'].median()) #결측값 변경 fillna
print('전처리전', np.std(df['distance']))
print('전처리후', np.std(df2['distance']))

전처리전 275.0161144074896
전처리후 267.0513844259766


이상치 제거   
orbital_period열의 이상치를 IQR 기법으로 제거하여  
이상치들의 합을 계산  
최종 결과만 print 출력  
### IQR = Q3-Q1
### Q1 - 1.5 * IQR, Q3 + 1.5 * IQR 를 벗어나면 이상치 

In [57]:
import seaborn as sns
import pandas as pd
sns.get_dataset_names()
del df
df= sns.load_dataset('planets')
print(df.head())

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009


In [71]:
Q25 = df['orbital_period'].quantile(0.25) #전체 수준에서 25%의 값
Q75 = df['orbital_period'].quantile(0.75)
IQR = Q25- Q75
min = Q25 - IQR * 1.5
max = Q75 + IQR * 1.5
print(IQR, min, max) #min, max 벗어나면 이상치 

-520.5624595 786.2862297500001 -254.83868925000013


In [72]:
df_outlier = df[(df['orbital_period']<=min) | (df['orbital_period']>=max)] #이상치
print(df_outlier['orbital_period'].sum())

1986894.255326


### 작업형 유형 2문제  - (1) 데이터 전처리   
seaborn 라이브러리에서 제공하는 샘플데이터 활용하여 실습  
sns.get_datanames_names()로 샘플데이터 종류를 확인할 수 있고 penguins를 활용  
데이터를 로드하여 df 변수에 할당  
종속 변수는 species 열임  

In [73]:
import seaborn as sns
df = sns.load_dataset('penguins')
print(df.head())
#데이터를 불러오면 결측치가 있는지 먼저 확인한다. 

  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female  


In [74]:
df.isna().sum() #결측치 유무 확인 - 결측치를 채워야한다. 

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [ ]:
#1. 결측치 제거 - 중앙값/평균 or 분포의 비율이 많은 값들을 넣어주기 

In [75]:
df['sex'].value_counts() # 성별 결측치는 남자로 넣고, 나머진 중앙값으로 일단 넣어보자. 

Male      168
Female    165
Name: sex, dtype: int64

In [78]:
#결측치 리스트화 시켜서 일단 missing 변수에
missing = ['bill_length_mm','bill_depth_mm', 'flipper_length_mm','body_mass_g']

for i in missing:
  df[i] = df[i].fillna(df[i].median()) 

df['sex']= df['sex'].fillna('Male')

In [79]:
df.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [82]:
df.head() 
#학습하기 좋도록 데이터를 문자-> 숫자로 preprocessing 
#라벨 인코딩

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen           39.10           18.7              181.0   
1  Adelie  Torgersen           39.50           17.4              186.0   
2  Adelie  Torgersen           40.30           18.0              195.0   
3  Adelie  Torgersen           44.45           17.3              197.0   
4  Adelie  Torgersen           36.70           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3       4050.0    Male  
4       3450.0  Female

In [84]:
from sklearn.preprocessing import LabelEncoder
label = ['species', 'island', 'sex']
df[label] = df[label].apply(LabelEncoder().fit_transform)

In [85]:
df.head() #문자열이 숫자로 바뀐 것 확인 가능 

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        0       2           39.10           18.7              181.0   
1        0       2           39.50           17.4              186.0   
2        0       2           40.30           18.0              195.0   
3        0       2           44.45           17.3              197.0   
4        0       2           36.70           19.3              193.0   

   body_mass_g  sex  
0       3750.0    1  
1       3800.0    0  
2       3250.0    0  
3       4050.0    1  
4       3450.0    0

In [86]:
df.dtypes #정수형을 카테고리 변수로(범주형 데이터는 숫자형 데이터가 아니라 인코딩이 필요하다) 

species                int64
island                 int64
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                    int64
dtype: object

In [88]:
#2. 데이터 타입 변환 작업, 더미 처리
# pandas를 불러와서 사용해야 한다. 
import pandas as pd
category = ['island','sex']
for i in category:
  df[i] = df[i].astype('category') #astype = 변수타입 변경 

df = pd.get_dummies(df) #더미처리 - 머신러닝 성능이 좋아지는 경우도 있어서 한다. 


In [105]:
df.dtypes

species                int64
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
island_0               uint8
island_1               uint8
island_2               uint8
sex_0                  uint8
sex_1                  uint8
body_mass_g_qcut       int64
dtype: object

In [89]:
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0           39.10           18.7              181.0       3750.0   
1        0           39.50           17.4              186.0       3800.0   
2        0           40.30           18.0              195.0       3250.0   
3        0           44.45           17.3              197.0       4050.0   
4        0           36.70           19.3              193.0       3450.0   

   island_0  island_1  island_2  sex_0  sex_1  
0         0         0         1      0      1  
1         0         0         1      1      0  
2         0         0         1      1      0  
3         0         0         1      0      1  
4         0         0         1      1      0

In [92]:
# 3. 파생변수 
# 새로운 변수를 만듦 
#qcut - 같은 개수로 구간 나누기 
df['body_mass_g_qcut'] = pd.qcut(df['body_mass_g'], 5, labels=False)
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0           39.10           18.7              181.0       3750.0   
1        0           39.50           17.4              186.0       3800.0   
2        0           40.30           18.0              195.0       3250.0   
3        0           44.45           17.3              197.0       4050.0   
4        0           36.70           19.3              193.0       3450.0   

   island_0  island_1  island_2  sex_0  sex_1  body_mass_g_qcut  
0         0         0         1      0      1                 1  
1         0         0         1      1      0                 1  
2         0         0         1      1      0                 0  
3         0         0         1      0      1                 2  
4         0         0         1      1      0                 0

In [93]:
df['body_mass_g_qcut'].value_counts()

0    71
1    70
2    68
4    68
3    67
Name: body_mass_g_qcut, dtype: int64

In [99]:
#4. 스케일 작업 - 모형 학습할 때 변수들 마다 단위가 다르기 때문에 
#실제 시험에서는 자동 생성이 안된다. 암기를 하는 것이 제일 좋고
# help함수를 이런 것을 이용하라 
# help('sklean.preprocessing')
from sklearn.preprocessing import MinMaxScaler
scaler = ['bill_length_mm', 'bill_depth_mm','flipper_length_mm','body_mass_g']
min = MinMaxScaler()
min.fit(df[scaler])
df[scaler]= min.transform(df[scaler])

In [100]:
df.head(). #0~1사이의 숫자로 다 스케일화 되었음. 

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0        0.254545       0.666667           0.152542     0.291667   
1        0        0.269091       0.511905           0.237288     0.305556   
2        0        0.298182       0.583333           0.389831     0.152778   
3        0        0.449091       0.500000           0.423729     0.375000   
4        0        0.167273       0.738095           0.355932     0.208333   

   island_0  island_1  island_2  sex_0  sex_1  body_mass_g_qcut  
0         0         0         1      0      1                 1  
1         0         0         1      1      0                 1  
2         0         0         1      1      0                 0  
3         0         0         1      0      1                 2  
4         0         0         1      1      0                 0

In [102]:
#5. 데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df['species'],test_size= 0.2, stratify= df['species'], random_state= 1)
#종속변수를 제거한 전체 행 독립변수로, 종속변수 넣고, 20%를 테스트용, 밸런스있게 골고루 있게 데이터 분리하는 옵션 stratify  

In [104]:
print('X_train', X_train.shape)
print('X_test', X_test.shape)
print('y_train', y_train.shape)
print('y_test', y_test.shape)

X_train (275, 10)
X_test (69, 10)
y_train (275,)
y_test (69,)


작업형 문제 2 - 모형 학습 및 평가  
랜덤포레스트 모형 

In [106]:
#6. 모형 학습
from sklearn.ensemble import RandomForestClassifier #배깅계열 
model1 = RandomForestClassifier()
model1.fit(X_train, y_train) #훈련용 데이터로 학습 
pred1 = model1.predict(X_test)

In [107]:
pred1 #예측된 결과값

array([0, 1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2,
       0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 2, 1, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0,
       2, 0, 1])

In [108]:
from sklearn.ensemble import AdaBoostClassifier #boost계열 
model2 = AdaBoostClassifier()
model2.fit(X_train,y_train)
pred2 = model2.predict(X_test)

In [109]:
pred2

array([0, 1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2,
       0, 1, 1, 0, 0, 0, 1, 2, 0, 0, 2, 1, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0,
       2, 0, 1])

In [110]:
#7. 서로 다른 기법 voting / 앙상블
from sklearn.ensemble import VotingClassifier
clf = VotingClassifier(estimators=[('rf',model1), ('ad',model2)], voting='hard') #voting option = soft = 확률 결합, 하드 - 정수형 
clf.fit(X_train,y_train) #학습 
pred3 = clf.predict(X_test)

In [111]:
pred3 #두개 모형 투표해서 예측 

array([0, 1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2,
       0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 2, 1, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0,
       2, 0, 1])

In [112]:
#8. 모형 평가 - 정확도 -> 다양하게 해보기
# 회귀모형은 평가가 또 다르다. 
from sklearn.metrics import accuracy_score
# form sklearn.metrics import classification_report 

print('랜포 정확도', accuracy_score(y_test, pred1))
print('에이다 정확도', accuracy_score(y_test, pred2))
print('보팅 정확도', accuracy_score(y_test, pred3)) 

랜포 정확도 1.0
에이다 정확도 0.9855072463768116
보팅 정확도 1.0


In [118]:
#9. 하이퍼 파라미터 튜닝 - 출제 범위에는 포함됨. 참고 정도 
from sklearn.model_selection import GridSearchCV #최적의 파라미터를 찾아주는 라이브러리 
parameters = {'n_estimators': [50, 100], 'max_depth':[4,6]} #서칭할 범위 
#의사 결정 트리를 몇개로 할 것이냐 몇개가 최적이냐. 얼마만큼 깊게 갈 것이냐. 
model4= RandomForestClassifier()
clf = GridSearchCV(estimator = model4, param_grid = parameters, cv=3)
clf.fit(X_train,y_train)
print('최적의 파라미터', clf.best_params_)

최적의 파라미터 {'max_depth': 4, 'n_estimators': 50}


In [120]:
#10. 예측값 저장 - 원하는 정답 형식으로 제출할 수 있게!! 
#파일명, 옵션 index=false로 하고 제출해야함. 
#True를 하면 알고리즘이 인식을 못해서 불합격! 
pd.DataFrame({'id':y_test.index, 'pred':pred3}).to_csv('00300.csv', index=False)

In [121]:
check = pd.read_csv('00300.csv')
check.head() #확인하기!! 

id  pred
0   57     0
1  173     1
2  213     1
3   50     0
4   25     0